[package]
name = "dera-local"
version = "0.1.0"
authors = ["Stanislav Bohm <spirali@kreatrix.org>"]
edition = "2018"

[dependencies]
dera = { path = "../dera" }
failure = "*"
log = "*"
futures = "*"
crossbeam = "*"
bytes = "*"